### ISSUE TITLE
Use git to update the database

### ISSUE THREAD

**Issue by zhou13** [jauhien/gs-pypi#3]
Hi jauhien,
    Currently when doing a `layman -S`, gs-pypi will always redownload tarball `https://codeload.github.com/jauhien/gs-pypi-db/tar.gz/bson`.  Since the snapshot is hosted on github, is it possible to use git to update the database to save the bandwidth and speed up the whole process?

**Comment by jauhien** [comment]
Hi zhou13,
thanks for your interest.

It is on my TODO list, I'll try to handle it when I have some time for this.

If you know python and wish to fix it, PR is welcome. It should not to be too difficult to fix.

(Also I have on my TODO list switch from using snapshots to dynamically generate ebuilds using pypi package, but it demands bigger changes in `g-sorcery`, so it will happen not in the nearest time).

**Comment by jauhien** [comment]
Pushed to master, available for installation with `=app-portage/g-sorcery-9999` from the tree (after changes are propagated to rsync). Will be released in the nearest time.

Commit: https://github.com/jauhien/gs-pypi/commit/7cfb0137dc6e59f7a6676a17c3e4d45dcb56321a

Support in `g-sorcery`: https://github.com/jauhien/g-sorcery/commit/29875e07c1749ddf895d2058046c17092d72732e https://github.com/jauhien/g-sorcery/commit/31ae597d8dbe927729df0af181a1312fbbe84130

**Comment by jauhien** [comment]
Released to the Gentoo tree: version 0.2.1 uses git sync by default. In case of any problems, please, feel free to open a separated issue.
