### ISSUE TITLE
sudo layman --add pypi FAILED

### ISSUE THREAD

**Issue by Aleksei-Badyaev** [jauhien/gs-pypi#4]
I configure gs-pypi:
[main]
package_manager=portage
[gs-pypi]
pypi_packages=msbackup

I added one package to list (my own pacgage) msbackup: https://pypi.python.org/pypi/msbackup

LOG::
$ sudo layman --add pypi
- Adding overlay...
- Overlay "pypi" is not an official. Continue install? [y/n]: y
- Running ... # ( cd /var/lib/layman/pypi  && /usr/bin/g-sorcery gs-pypi -o /var/lib/layman/pypi -r pypi sync )
  Клонирование в «/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/persistent/remote»…
  remote: Counting objects: 7, done.
  remote: Compressing objects: 100% (5/5), done.
  remote: Total 7 (delta 0), reused 5 (delta 0), pack-reused 0
  Распаковка объектов: 100% (7/7), готово.
  Проверка соединения… готово.
- copy files to an actual database
  «/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/persistent/remote/categories.json» -> «/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/categories.json»
  «/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/persistent/remote/dev-python» -> «/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/dev-python»
  «/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/persistent/remote/dev-python/packages.bson» -> «/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/dev-python/packages.bson
  »
  «/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/persistent/remote/manifest.json» -> «/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/manifest.json»
  «/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/persistent/remote/metadata.json» -> «/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/metadata.json»
- Running g-sorcery... # ( cd /var/lib/layman/pypi  && /usr/bin/g-sorcery gs-pypi -o /var/lib/layman/pypi generate-tree )
- tree generation
- no package with name msbackup found

Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/g-sorcery", line 18, in <module>
    sys.exit(g_sorcery.main())
  File "/usr/lib/python2.7/site-packages/g_sorcery/g_sorcery.py", line 68, in main
    return backend.instance(sys.argv[2:], config, global_config)
  File "/usr/lib/python2.7/site-packages/g_sorcery/backend.py", line 652, in **call**
    return args.func(args, config, global_config)
  File "/usr/lib/python2.7/site-packages/g_sorcery/backend.py", line 530, in generate_tree
    dependencies |= self.get_dependencies(pkg_db, pkg)
  File "/usr/lib/python2.7/site-packages/g_sorcery/backend.py", line 351, in get_dependencies
    raise DependencyError(error)
g_sorcery.exceptions.DependencyError: no package with name msbackup found
- Failure result returned from g-sorcery
- Adding repository "pypi" failed! Possible remains of the operation have NOT been removed and may be left at "/var/lib/layman/pypi". Please remove them manually if 
  required.
- CLI: Errors occurred processing action add
- Adding repository "pypi" failed! Possible remains of the operation have NOT been removed and may be left at "/var/lib/layman/pypi". Please remove them manually if 
  required.

**Comment by jauhien** [comment]
There is no such package in DB. Interesting, I'll look at it.

**Comment by jauhien** [comment]
I see what's the problem: the package is too new. Currently gs-pypi database is offline and is updated roughly once per month. I'll update it in the nearest time to have your package there.

**Comment by Aleksei-Badyaev** [comment]
Thank you (sorry for my bad English) !

**Comment by jauhien** [comment]
Ok, your package was added. I have plans to change gs-pypi to use upstream tools (next year) but until that the database is synced ~ once per month.

Also I need to add python 3.5 and remove python 3.3 from ebuilds (next month).

**Comment by jauhien** [comment]
Btw, if you're a Gentoo user, you could consider packaging your package as normal one in the tree (or one of overlays). Now it is quite easy, you just need to make a PR to `gentoo/gentoo` repo with your ebuild. That's a way better than using ebuild generator (which is used only because there is much more packages then maintainers ;-) ). And you can speak Russian to me if you are not very comfortable with English. )

**Comment by Aleksei-Badyaev** [comment]
Спасибо за совет! Я доработаю свой проект и подготовлю ebuild для репозитория Gentoo.
